import { useState, useMemo } from "react";

const initalFriends = [
    'Emily Johnson',
    'David Smith',
    'Sarah Davis',
    'Michael Wilson',
    'Jessica Brown',
    'Brian Miller',
    'Ashley Taylor',
    'Christopher Anderson',
    'Olivia Martinez',
    'Matthew Moore',
    'Lauren Turner',
    'Daniel Rodriguez',
    'Chloe Garcia',
    'Tyler Thomas',
    'Sophia Lewis',
    'Kevin Hill',
    'Natalie Adams',
    'Benjamin Turner',
    'Emma Martinez',
    'Joshua Walker',
    'Madison White',
    'Ryan Scott',
    'Avery Parker',
    'Ethan Collins',
    'Hannah Evans',
    'Nicholas Baker',
    'Ava Phillips',
    'Jacob Mitchell',
    'Grace Carter',
    'Justin Lee',
    'Lily Foster',
    'Caleb Turner',
    'Aria Miller',
    'Jason Johnson',
    'Mia Davis',
    'Logan Brown',
    'Savannah Wright',
    'Isaac Clark',
    'Zoe Allen',
    'Nathan King',
    'Amelia Wilson',
    'Brandon Taylor',
    'Harper Moore',
    'Dylan Adams',
    'Victoria Scott',
    'Mason White',
    'Sydney Turner',
    'Christopher Hall',
    'Penelope Smith',
    'Zachary Turner',
    'Addison Hill',
    'Christian Martinez',
    'Leah Lewis',
    'Owen Parker',
    'Elizabeth Anderson',
    'Gabriel Davis',
    'Kaylee Wright',
    'Andrew Moore',
    'Scarlett Phillips',
    'Cole Johnson',
    'Isabella Thomas',
    'Samuel Carter',
    'Eleanor Allen',
    'Carter Harris',
    'Abigail Garcia',
    'Luke Foster',
    'Paisley Clark',
    'Jordan Mitchell',
    'Isabelle King',
    'Gavin Taylor',
    'Lillian Wright',
    'Caleb Turner',
    'Skylar Hill',
    'Josiah Parker',
    'Nora Wilson',
    'Colton Adams',
    'Taylor Smith',
    'Madelyn Evans',
    'Aidan Baker',
    'Maya Scott',
    'Eli Anderson',
    'Piper White',
    'Dominic Martinez',
    'Alexis Johnson',
    'Henry Moore',
    'Clara Turner',
    'Sebastian Davis',
    'Makayla Harris',
    'Wyatt Foster',
    'Adeline Allen',
    'Tristan Phillips',
    'Kayla Brown',
    'Lincoln Wright',
    'Raelynn Mitchell',
    'Miles Taylor',
    'Gabriella Clark',
    'Brayden King',
    'Ariel Hill',
    'Jackson Turner',
    'Sofia White',
    'Lucas Miller',
    'Hailey Wilson',
    'Gavin Harris',
    'Emma Turner',
    'Brandon Davis',
    'Olivia White',
    'Zachary Clark',
    'Ava Anderson',
    'Daniel Parker',
    'Grace Smith',
    'Ethan Turner',
    'Abigail Brown',
    'Noah Wright',
    'Sophia Adams',
    'Christopher Lee',
    'Mia Taylor',
    'Ryan Moore',
    'Avery Mitchell',
    'Hannah Foster',
    'Logan Phillips',
    'Emily Evans',
    'Carter Taylor',
    'Savannah Martinez',
    'Isaac Baker',
    'Alexis King',
    'Joshua Hill',
    'Addison Turner',
    'Madison Harris',
    'Nicholas Carter',
    'Chloe Scott',
    'Jacob Wilson',
    'Lily Moore',
    'Benjamin Miller',
    'Aria Taylor',
    'Brayden Johnson',
    'Amelia Davis',
    'Gabriel Smith',
    'Makayla Wright',
    'Nathan Foster',
    'Peyton Martinez',
    'Leah Anderson',
    'Justin Brown',
    'Natalie Turner',
    'Colton Evans',
    'Zoe Baker',
    'Jordan Mitchell',
    'Aria White',
    'Jayden Hall',
    'Brooklyn Taylor',
    'Christian Wright',
    'Isabel Mitchell',
    'Leo Parker',
    'Ella Adams',
    'Liam Foster',
    'Charlotte Baker',
    'Julian Mitchell',
    'Audrey Wright',
    'Gavin Lewis',
    'Aubrey Turner',
    'Henry Hill',
    'Penelope Evans',
    'Lucas Davis',
    'Violet Mitchell',
    'Owen Baker',
    'Paisley Turner',
    'Xavier Moore',
    'Brooklyn Anderson',
    'Elijah Harris',
    'Layla Davis',
    'Jaxon Foster',
    'Kylie Martinez',
    'Cooper White',
    'Autumn Turner',
    'Dylan Harris',
    'Avery Parker',
    'Adrian Davis',
    'Emery Martinez',
    'Grayson Turner',
    'Kinsley Wright',
    'Brayden Baker',
    'Adeline Turner',
    'Landon Mitchell',
    'Alexa Davis',
    'Sebastian Wright',
    'Harper Martinez',
    'Jackson Foster',
    'Evelyn Turner',
    'Cameron Baker',
    'Luna Martinez',
    'Aiden Turner',
    'Sofia Harris',
    'Jack Anderson',
    'Elise Wright',
    'Levi Turner',
    'Amara Davis',
    'Sawyer Harris',
    'Aubrey Turner',
    'Zane Baker',
    'Mila Davis',
    'Zachary Harris',
    'Adalynn Turner',
    'Hayden Anderson',
    'Riley Wright',
    'Jace Turner',
    'Khloe Davis',
    'Luca Harris',
    'Aria Turner',
    'Tristan Baker',
    'Hadley Wright',
    'Gabriel Harris',
    'Nova Turner',
    'Easton Davis',
    'Lila Martinez',
    'Silas Baker',
    'Nora Wright',
    'Max Turner',
    'Fiona Harris',
    'Axel Davis',
    'Alessia Martinez',
    'Kai Baker',
    'Liam Harris',
    'Eli Turner',
    'Stella Wright',
    'Harley Davis',
    'Cora Baker',
    'Chase Harris',
    'Isabella Turner',
    'Caleb Wright',
    'Felicity Davis',
];

export function Friends() {
    const [count, setCount] = useState(0);
    const [friends] = useState(initalFriends);
    const [filter, setFilter] = useState('');

    const visibleFriends = useMemo(() => {
        console.log('Friends filter'); 
        return friends.filter(friend => friend.toLowerCase().includes(filter));
    }, [filter, friends])

    // const visibleFriends = (() => {
    //     console.log('Friends filter'); 
    //     return friends.filter(friend => friend.toLowerCase().includes(filter));
    // })();

    return (
        <div>
            <hr />
            <button onClick={() => setCount(c => c + 1)}>
                Count: {count}
            </button>
            <code>
                цей компонент не впливає на фільтрацію 
            </code> 
            <h2>Friends list:</h2>
            <p>Find your friends</p>
            <input onChange={e => setFilter(e.target.value)} value={filter} />
            <ul>
                {visibleFriends.map((friend, idx) => (
                    <li key={idx}>{friend}</li>
                ))}
            </ul>
        </div>
    )
}